### ISSUE TITLE
test_SR_IOV_BondVF requests PF2 and has has KeyError: 'pf2' but isn't requested in testbed.yaml example

### ISSUE THREAD

**Issue by javanhut** [redhat-partner-solutions/rhel-sriov-test#144]
[SR-IOV Test Report.pdf](https://github.com/redhat-partner-solutions/rhel-sriov-test/files/10945635/SR-IOV.Test.Report.pdf)
This error can be fixed by adding a pf2 to the yaml file however, it isn't specified in the template or example for the testbed.

**Comment by jianzzha** [comment]
Thanks for logging this issue Javan. It was addressed by https://github.com/redhat-partner-solutions/rhel-sriov-test/pull/143
