### ISSUE TITLE
testbed_template.yaml needs some tweaks

### ISSUE THREAD

**Issue by PatrickKutch** [redhat-partner-solutions/rhel-sriov-test#91]
for the PF, the example PCIe address is that of a VF.  
Better examples might be:
PF      pci: "0000:18:00.0"
VF      pci: "0000:18:01.0"

Also, is a nitpick, but it is pcie, not pci.

**Comment by dkosteck** [comment]
Done via https://github.com/redhat-partner-solutions/rhel-sriov-test/pull/145
