### ISSUE TITLE
running container is hard-coded

### ISSUE THREAD

**Issue by PatrickKutch** [redhat-partner-solutions/rhel-sriov-test#93]
Within tests/common/test_exec.py:

    testpmd_podman_cmd = (
        "podman run -it --rm --privileged -v /sys:/sys "
        "-v /dev:/dev -v /lib/modules:/lib/modules "
        "--cpuset-cpus 30,32,34 docker.io/patrickkutch/dpdk:v21.11 "
        "dpdk-testpmd -l 30,32,34 -n 4 -a " + vf_pci + " -- --nb-cores=2 -i"
    )

I would like to see much of this come from a config file.  I see the testbed.yaml has pmd_cpus
maybe have a dpdk section under dut that has something like:
  dpdk:
    pmd_cpus: "2-6,8,10-15"
    container: "docker.io/patrickkutch/dpdk:v21.11.5"
    launcher: 
      cmd: "podman"
      parameters: "run -it --rm --privileged -v /sys:/sys -v /dev:/dev -v /lib/modules:/lib/modules"

**Comment by dkosteck** [comment]
Done via #146
