### ISSUE TITLE
dpdk tests do not seem to use hugepages

### ISSUE THREAD

**Issue by PatrickKutch** [redhat-partner-solutions/rhel-sriov-test#94]
looking in test_exec.py, I do not see the container being given access to hugepages.

When I run the containerized DPDK, I have:
-v /sys/kernel/mm/hugepages:/sys/kernel/mm/hugepages included.

I believe if you don't do this, the performance could be reduced.

I also don't see in any of the test cases actually creating huge pages.

We should disucss.

**Comment by jianzzha** [comment]
we forgot to documente this: we have kargs that set up static huge page, iommu etc, for example: "intel_iommu=on iommu=pt default_hugepagesz=1G hugepagesz=1G hugepages=16". But you bring up a good point on what should goes to the kargs and who should be done in the test code. Maybe 1GB hugepage need to set on the kargs but 2M huge page should be set dynamically in the test code. Especially when we start to work on the multiple container start/kill test case, this dynamic set up 2M hugepage seems to be a good idea.

**Comment by jianzzha** [comment]
https://github.com/redhat-partner-solutions/rhel-sriov-test/pull/104
